### ISSUE TITLE
How can I show it for all I have the group Owner and my default group is Spieler and I have many Groups?

### ISSUE THREAD

**Issue by Gipfel** [Ktar5/Info-Board#134]
How can I show it for all I have the group Owner and my default group is Spieler and I have many more Groups?

**Comment by pixar02** [comment]
In the default config.yml there is an example that uses the word Global and Default. By global we mean that it doesn't matter in which world you are and by default we mean that it doesn't matter which rank you are. 

So if you want a specific board for your rank Owner you create a new board and instead of using default you use the name Owner (OR the name of your group).

 If you want to display a scoreboard in a certain world you create a new board and change the word Global to the world you want to show it in.
