### ISSUE TITLE
Bug with worldguard

### ISSUE THREAD

**Issue by ThisIsJuli3N** [Ktar5/Info-Board#135]
Hi, on my server i've got an error with InfoBoard and worldguard when they work together at the same time : 

![error](https://user-images.githubusercontent.com/44033933/46752393-57e04180-ccbd-11e8-8711-4c4c486d0c6e.png)

Do you have any issue pls ?

thanks for your help.

**Comment by pixar02** [comment]
WorldGuard hasn't been updated for 1.13.X yet. So trying to run an outdated plugin on a new platform is a bit stupid. I don't think it will take long for Worldguard to realise this an update. Also the reason Worldguard won't work on the new version is because of the way 1.13.X handles the Block names and ID's. ID's have been removed but since all plugin authors want backwards compatibility they have to find a way arround the ID and convert them to the Names.

**Comment by TheIntelloBox** [comment]
WorldGuard's dev builds are in 1.13.1. :D
